### ISSUE TITLE
Can't start SmartNode on Windows 10

### ISSUE THREAD

**Issue by MiMoHo** [SmartCash/electrum-smart#5]
Searched for my external IP by https://whatsmyip.com in my home WiFi network without a dedicated external IP and deactivated my firewall, but the node keeps telling me "something went wrong" when clicking "Start alias". Can't input debug information, as nothing happens when I press "show report contents".
I am using Windows 10 with latest updates.

**Comment by rc125** [comment]
Hey @MiMoHo! 

To get the log in windows, just redirect the output to a file, like this: `electrum-smart.exe -v >> logfile.log` then, send me the log here.

Report issues functionality was not working properly, I just fixed in this commit https://github.com/SmartCash/electrum-smart/commit/22730c0b8df77b4adf9cb9a7a1bb72526b183243. In the next few days I will create a new build with the bug fixes.
